codeit-part4-8team-project/main

src/App.tsx
tsconfig.json
vite.config.ts

alias경로 설정 후 페이지 잘 뜨는 지 확인 했습니다! 
ts.confing파일에서 
"compilerOptions": {
"baseUrl": "./src",
"paths": {
"@/*": ["*"]
},
이렇게 설정을 안해서 잘 작동이 안됐던 것 같습니다!

feat: alias 경로 추가 설정

---

.prettierrc.json
package-lock.json
package.json
src/index.css
src/main.tsx
tailwind.config.js

tailwind 설정
tailwind, postcss 적용 설정
prettier에 tailwind 플러그인 추가
임시로 global css 작성했습니다.
prettier-plugin-tailwindcss : tailwind 클래스명 정렬 위해

Feat: TailwindCSS, global style 셋팅

---

.prettierrc.json

- import문 순서 정렬 기준 추가/수정
변경 사항 이게 전부입니다.
- @types로 시작하는 라이브러리 상단으로 가도록
- 정렬 기준에 pages 폴더 추가 
- 없음

Style: 프리티어 import문 정렬 기준 추가 및 수정

---

src/components/common/Modal.tsx
src/pages/HomePage.tsx

- 모달레이아웃 작업 완료 했습니다
-
- 폰트크기, 색상, children , 제외하고 토글가능하게끔, props기본세팅 해놨습니다 ^_^
-

Modal layout 

---

public/images/Close.svg
public/images/Plus.svg
src/components/common/Button.tsx
src/components/common/Modal.tsx

- 버튼 컴포넌트 작업했고, 피그마 데브모드 소은님, 채빈님이 해결해줘서 모달 컴포넌트에 Close이미지 추가했습니다.
-
-
- 아직 디자인이 완성되지않아 색상은 뒤죽박죽입니다.. 이해 바랍니다 ^_^

Feat: Button common components, Refactor: Modal Img

---

src/components/common/SideBar.tsx
src/pages/TeamsPage.tsx

- 와이어프레임 참고하여 사이드 바 ui 구현
- 다른 건 없습니다. ui 작업하며 구조만 잡았습니다.
- 와이어프레임이라 구조만 잡아도 되지만 테일윈드 연습 겸 피그마 그대로 UI 구현해보았습니다.
- 컴포넌트 하나에 전부 작성했는데 나중에 작업하면서 컴포넌트별로 나누려고 합니다.
- 테일윈드 전역에 폰트 사이즈 62.5%로 설정 되어 있던데 그러면 rem 단위로 계산해야 하는지? 근데 테일윈드라 그게 의미가 있는지? 헷갈립니다. 내일 얘기해보면 좋겠습니다.
- 테일윈드 처음이라 아직 적응이 안 되네요 ㅎㅎ 사이즈 값은 거의 대부분 대괄호 사용해서 arbitrary values로 줬는데 다른 분들 예시 보고 익숙해지면 정식 ui 작업할 때는 테일윈드에서 주는 값으로 할 예정입니다.

Design: 사이드바 UI 구조

---

public/images/EllipseColor.svg
public/images/dorpdown.svg
src/components/Modal/GroupModal.tsx
src/components/common/ModalInput.tsx
src/components/common/ModalLayout.tsx
src/pages/HomePage.tsx

- 모달 인풋 따로 컴포넌트로 만들어서 작업했습니다.
- 그룹생성 모달 만들었습니다.
- Modal -> LayoutModal 네이밍 변경했습니다.
-
- 기능적으로 넣은건 딱히 없고 inputValue,onClick만 물려놓았습니다
- 이미지를 보시면 아시겠지만 박스에 그림자 넣는 테일윈드 코드 커스텀을 도저히 모르겠어서... 그림자 넣는거 커스터마이징 어떻게 해야할지 아시겠나요??
- 지현님과 얘기 나눈대로 컬러쪽은 더 이상 작업하지 않고 그대로 올립니다. 수정해야할 사항이 생길것 같아요

Feat: ModalInput, GroupModal Components

---

public/images/filter.svg
src/App.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/DateBox.tsx
src/components/SchedulesPage/Schedules.tsx
src/components/common/Button.tsx
src/components/common/ModalLayout.tsx
src/pages/TeamSchedulesPage.tsx

-팀 스캐줄, 나의 스캐줄 페이지 레이아웃 구성 후 일정생성하면 모달 열리게끔 했습니다. 
-
-모달이 열리는데 가운데로 오지 않아서 기본 모달레이아웃 페이지에 right적용했습니다. 
- 수정사항 확인하시고 문제 있으면 알려주세요 ! 
-필겸님이 만들어주신 일정생성 모달로 수정 & 스캐줄 컴포넌트 추가기능 구현해서 다시 PR올리겠습니다.

Feat: Complete teamSchedulesPage-soeun

---

public/data/TeamsMember.json
src/components/Modal/MemberProfile.tsx
src/components/TeamMemberList.tsx
src/pages/HomePage.tsx

-  팀멤버조회 기능, 멤버 이미지 클릭시 모달창 구현했습니다
-
- 
- ```  const getMemberId = () => {
if (memberId === null) {
return null;
}
return members.find((member) => member.userId === memberId);
}; 
`
이 부분이 좀 이상한것 같긴한데... MockDate로 만들다 보니 다소 어색한 감이 있는것 같아요 나중에 api연동 시킬때 자연스럽게 만들어 보겠습니다!

teamMemberList 구현, 멤버이미지 클릭시 모달창 구현

---

tailwind.config.js

tailwindcss 색상 설정. 셀프 머지 바로 하겠습니다.
-
-
-

Setting: Add color variable on tailwindconfig

---

src/App.tsx
src/contexts/UserProvider.tsx
src/hooks/useAxios.ts

1. 요청 2회 넘어가는 문제 해결하기 위해 axios 훅 내부 메모이제이션 추가
2. user 정보 받아 쓰는 쪽, 업데이트 하는 쪽에서 쓸 useUserContext 훅 작성
사용법
```js
const { user, setUser } = useUserContext();
```
전역으로 유저 상태 관리할 useUserContext 작성.
새로고침 포함 여러 이유로 user 상태가 초기화 될 경우 consumer 쪽에서 다시 요청할 필요 없이 context 내부에서 api/user로 재요청 보내 업데이트 하도록 함.
-

Feat: user context 구현

---

src/App.tsx
src/contexts/SignupStepProvider.tsx
src/contexts/UserProvider.tsx
src/hooks/useAxios.ts

스테이징 빼먹었더니 에러나서 일단 바로 올리고 셀프머지 하겠습니다 
-
-
-
-

Feat: signup페이지 context 작성

---

src/components/common/sideBar/constants.tsx

Fix: 사이드바 /me 경로 /user로 수정

---

src/components/TeamsPage/TeamBar.tsx
src/components/TeamsPage/TeamPageLayout.tsx
src/components/common/NoCard.tsx
src/components/common/sideBar/BoardList.tsx
src/components/common/sideBar/GroupList.tsx
src/components/common/sideBar/SideBar.tsx
src/components/common/sideBar/constants.tsx
src/components/kanbanBoard/IssueList.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/contexts/TeamProvider.tsx
src/pages/team/TeamContents.tsx
src/pages/team/TeamKanban.tsx
src/pages/team/TeamMembers.tsx
src/pages/team/TeamNotice.tsx
src/types/issueTypes.ts
src/types/teamTypes.ts

- 사이드바 / 이슈 / 팀 백엔드 api 연동
- 사이드바 / 이슈 / 팀 api로 데이터 받아올 수 있도록 구현했습니다.
-

Feat: 사이드바 / 이슈 / 팀 백엔드 api 연동

---

src/contexts/PageProvider.tsx

- 페이지네이션 구현 PR에 바뀐 페이지명이 반영되지 않아 그 부분만 고쳤습니다.
-
-
- 지금 오류 나고 있는 상황이라 바로 머지하겠습니다.

Fix: 단수 명사로 바뀐 페이지명 반영되지 않았던 문제 해결

---

src/components/TeamsPage/TeamBar.tsx
src/components/kanbanBoard/IssueItem.tsx
src/components/kanbanBoard/IssueList.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/pages/UserMainPage.tsx
src/pages/team/TeamIssuesPage.tsx
src/pages/team/TeamMainPage.tsx
src/types/issueTypes.ts

- 팀 페이지 전환 시 데이터가 업데이트 되지 않던 문제 해결
- 팀 이슈 페이지에서 팀 데이터가 불러와지지 않던 문제 해결
- 플로팅 버튼 삽입으로 생겼던 불필요한 간격 해결 (UI)
-
-

Fix: 데이터 불러오기 관련 문제 해결

---

src/components/Modal/EditProfileModal.tsx
src/components/Modal/ManageTeamHistoryModal.tsx
src/components/ModalWrapper.tsx
src/components/Mypage/MyProfileCard.tsx
src/components/Mypage/MyTeamHistory.tsx
src/components/Mypage/MyTeamHistoryRow.tsx
src/components/Mypage/MyTeamHistoryTable.tsx
src/components/Mypage/NoTeamRow.tsx
src/components/common/BoardSection.tsx
src/components/common/Dropdown.tsx
src/components/common/EditProfileForm.tsx
src/components/common/card/ProfileCard.tsx
src/constants/Page.tsx
src/constants/Team.tsx
src/constants/defaultPageData.ts
src/contexts/PageProvider.tsx
src/contexts/UserProvider.tsx
src/hooks/useMyTeam.ts
src/pages/UserMyPage.tsx
src/types/teamTypes.ts
src/types/user.ts

코드 난장판인데 시간은 없고 양은 많아서 어쩔 수 없네요 ㅠㅠ 일단 구현부터...
지선님 페이지네이션에 mypage도 추가했습니다. 
그룹 관리 모달에서 확인 받을 만한 부분 있어서 이따 미팅 때 여쭤보고 반영하겠습니다. onSubmit 내부 로직만 보내면 끝나는 거라 금방 업데이트 가능합니다.

Feat: user/:userID/mypage 구현

---

src/components/MainPage/MainSchedules.tsx
src/components/MainPage/WeekDisplay.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/DateBox.tsx
src/components/SchedulesPage/Tiem.tsx
src/pages/HomePage.tsx

시간  설정 진행중

---

src/hooks/useMember.ts

유저 페이지 에러 만들어서 고치고 바이패스 머지합니다
번거로우시겠지만 풀 다시 받으시면 풀려요 ㅠㅠ
-
-
-

Fix: useMember.tsx 로 인한 유저페이지 에러 수정

---

src/components/announcement/AnnouncementItem.tsx
src/components/announcement/AnnouncementPageList.tsx
src/components/common/ItemDropDown.tsx

Feat: 공지사항 고정 기능 추가

---

src/components/SchedulesPage/Time.tsx
src/components/common/Nav.tsx

-모달에 들어가는 시간설정 부분, minute부분 스크롤 설정했습니다! 
-네브바 팀초대 알림창 뜨도록 구현했습니다. (읽지 않음 읽음 표시는 모달 연결 후 해야할 것 같습니다! )
-
-
-알림창 바깥쪽 클릭하면 닫히도록 하고 싶은데 잘 안됐습니다 혹시 아시는 분들은 알려주시면 감사하겠습니다! 
일단 닫힘 버튼 만들고 클릭하면 닫히도록 했습니다!
-

Feat: 시간설정 부분 스크롤 추가, 네브바 알림창 설정

---

src/components/Modal/EditProfileModal.tsx
src/components/Modal/ManageTeamHistoryModal.tsx
src/components/Mypage/MyTeamHistory.tsx
src/components/Mypage/MyTeamHistoryRow.tsx
src/components/Mypage/MyTeamHistoryTable.tsx
src/components/common/Input.tsx
src/pages/UserMyPage.tsx

그룹 히스토리 모달에 api 연결해서 완성
인풋 유효성 메시지 노드 공통 컴포넌트 작성.
근데 회원탈퇴나 로그아웃 api는 있는데 디자인은 못찾겠네요

Feat: 마이페이지 완성

---

src/App.tsx
src/components/Modal/AnnouncementEditModal.tsx
src/components/Modal/AnnouncementModal.tsx
src/components/Modal/DetailsScheduleModal.tsx
src/components/Modal/FreeBoardDetail.tsx
src/components/Modal/FreeBoardEdit.tsx
src/components/Modal/FreeBoardModal.tsx
src/components/Modal/GroupEditModal.tsx
src/components/Modal/GroupModal.tsx
src/components/Modal/InvitationGroupModal.tsx
src/components/Modal/IssuesModal.tsx
src/components/Modal/MyIssuesModal.tsx
src/components/Modal/NotMeIssuesModal.tsx
src/components/Modal/ScheduleModal.tsx
src/components/TeamsPage/TeamPageLayout.tsx
src/components/common/modal/AfterApprovalModal.tsx
src/components/common/modal/GroupList.tsx
src/components/common/modal/ModalColorToggle.tsx
src/components/common/modal/ModalLayout.tsx
src/pages/HomePage.tsx

프롭으로 팀,스케줄,이슈 아이디 받아야합니다

---

src/App.tsx
src/constants/Page.tsx

- 멘토님께서 말씀해주신 방법대로 코드 스플리팅 코드 추가했습니다.
- App 컴포넌트에 Suspense 추가했고 fallback에는 로딩 중에 대한 디자인 없으니 일단 단순히 `<div>로딩 중</div>` 넣어두었습니다.
-
-

Refactor: 코드 스플리팅

---

src/assets/PersonIcon.tsx
src/components/common/BoardSection.tsx
src/constants/Page.tsx
src/pages/UserMainPage.tsx
src/pages/team/TeamMainPage.tsx

- 메인 페이지에 주간 캘린더 주석해제했습니다.
- 마이페이지 아이콘 변경
-
-
-

Feat: 메인페이지 캘린더 주석 해제 및 마이페이지 아이콘 설정

---

src/components/Post/PostList.tsx
src/components/common/Filter.tsx
src/contexts/PageProvider.tsx
src/hooks/useIssue.ts
src/pages/UserIssuesPage.tsx
src/pages/UserPostsPage.tsx

그룹 필터 추가했습니다. 수정해야 할 부분 있기는 한데 일단 대강 동작하게라도 올립니다 😂
-
-

Feat: UserPostsPage & UserIssuesPage 그룹필터 추가

---

src/App.tsx
src/components/Modal/GroupEditModal.tsx
src/components/Modal/GroupModal.tsx
src/components/Modal/IssuesModal.tsx
src/components/Modal/ScheduleModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/DateBox.tsx
src/components/SchedulesPage/Time.tsx
src/components/common/Nav.tsx
src/components/common/modal/ModalCalendar.tsx
src/components/common/modal/ModalCalendarInput.tsx
src/components/common/modal/ModalInput.tsx
src/components/common/modal/ModalScheduleCalendarInput.tsx

-모달에 달력있는 부분 달력 클릭하면 값에 담기도록 했습니다
-캘린더  칸별로 클릭해도 모달 뜨도록 해놨습니다 
-
-
-저 useAxios안쓴 부분 있는데 그것도 바꿔서 PR올리겠습니다!

Feat:모달에 달력클릭하면 인풋 값으로 연결

---

src/components/Modal/FreeBoardModal.tsx
src/components/Post/TeamPostList.tsx
src/components/Post/UserPostList.tsx
src/pages/UserPostsPage.tsx
src/pages/team/TeamPostsPage.tsx

- 필겸님 자유게시판 모달 변경사항으로 발생한 빌드 에러 수정했습니다.
- 기존의 PostList를 유저, 팀으로 나눠버렸습니다. (지금 상황에선..ㅠ)
-
-
-

Fix: 빌드 에러 수정

---

src/components/SchedulesPage/AllDay.tsx
src/components/common/Nav.tsx
src/components/common/modal/ModalCalendarInput.tsx

Refactor-soeun 빌드시 오류 제거 

---

src/components/Modal/EditProfileModal.tsx
src/components/SignupPage/EnterUserStepContent.tsx
src/components/SignupPage/SignupLayout.tsx
src/contexts/ModalProvider.tsx
src/hooks/useAxios.ts

Fix: 모달 id 생성 useId로 변경

---

src/components/Modal/groupMemberInviteModal.tsx
src/components/Post/PostItem.tsx
src/components/TeamsPage/TeamBar.tsx
src/components/kanbanBoard/IssueItem.tsx
src/components/kanbanBoard/IssueList.tsx

- 필겸님께서 작업해주신 상세보기 모달 연결했습니다. 
- @MoonPillGyeom 수정 필요한 부분은 스크린샷에 같이 올려두겠습니다.
- 전반적으로 UI 부분 다시 봐주셔야 할 것 같아요 (아이콘 없애기, 테두리 border-radius, 레이아웃 등)
- 이름 부분은 유저네임이 아니라 이름으로 들어가야 합니다!
- 내용 위치도 좋아요버튼 위로 올라가게 수정 부탁드립니다
- 디자인 시안:
- 전반적으로 UI 부분 다시 봐주셔야 할 것 같아요 (아이콘 없애기, 테두리 border-radius, 버튼 간격 등)
- 제가 지금 다른 팀원이 속한 이슈가 없어서 내 이슈가 아닌 경우 테스트는 아직 못 해봤습니다
- 버튼에는 '그룹 생성하기'라고 되어 있는데 지현님이 놓치신 것 같아요! '초대하기'가 더 낫지 않을까 싶습니다.
- 근데 초대버튼 클릭하면 500에러가 뜨네요...? 스웨거에서 확인해보면 200으로 잘 뜨는 것 보니 서버에 문제가 있는 건 아닌 것 같은데 확인 부탁드립니다!
-
- 필겸님 모달 전체적으로 border-radius 수정 부탁드립니다!!
- GroupMemberInviteModal은 컴포넌트 이름이 소문자로 시작해서 그 아래로 쭉 에러가 뜨고 있어서 그 부분이랑 빈 객체로 에러나는 부분만 제가 수정했습니다.

Feat: 상세보기 모달 연결

---

src/components/Modal/FreeBoardModal.tsx
src/components/Post/PostItem.tsx

Refactor: import Img

---

src/assets/assets/circleDark.svg
src/assets/assets/circleLight.svg
src/pages/HomePage.tsx

온보딩 완료git add .

---

src/components/Post/PostItem.tsx
src/components/Post/TeamPostList.tsx
src/components/Post/UserPostList.tsx
src/components/common/Board.tsx
src/pages/UserIssuesPage.tsx
src/pages/UserPostsPage.tsx
src/pages/team/TeamPostsPage.tsx

Fix: UI 수정

---

src/components/MainPage/MainSchedules.tsx
src/components/MainPage/WeekDisplay.tsx
src/components/Modal/IssuesModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/GroupFilter.tsx
src/components/common/modal/ModalScheduleCalendarInput.tsx
src/pages/HomePage.tsx
src/routes/PrivateRoutes.tsx

-주간 달력 수정해서 데이터 잘 받아오게끔 했습니다! 
-온보딩 페이지 스타일 살짝 수정했습니다! 
-
-
-

주간달력 안나오는 부분 수정& 온보딩 스타일 수정

---

src/App.tsx
src/components/Modal/EditProfileModal.tsx
src/components/Modal/ManageTeamHistoryModal.tsx
src/components/Mypage/MyTeamHistoryTable.tsx
src/components/SignupPage/EnterUserStepContent.tsx
src/components/members/MemberRow.tsx
src/components/members/MemberTable.tsx

각 페이지들에서 기능 문제, 스타일 문제 모두 수정했습니다. 근데 지금 다시 500 에러나는 api들이 있어서 한 번 여쭤봐야할 것 같습니다.
-
-
-

Fix: 멤버리스트, 회원가입, 마이페이지 기능 문제 전체 수정

---

src/components/Modal/ScheduleModal.tsx
src/components/SchedulesPage/AddScheduleModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/Time.tsx
src/components/common/modal/ModalScheduleCalendarInput.tsx

-스캐줄 페이지 일정추가모달에서 시간값과 같이 인풋에 들어가고 데이터가 보내지게끔 수정
-일정추가가 되면 자동 리렌더링 되게끔 수정
-
-
-Allday파일의 AddScheduleModal의 스타일이 먹히지 않고 있습니다... 혹시 해결방법 아신다면 코멘트 달아주시면 감사하겠습니다!

Fixed: 일정추가되면 리렌더링 가능, 모달 시간 설정부분 수정

---

src/components/Modal/FreeBoardModal.tsx
src/components/Modal/IssuesModal.tsx

…st fetch teamId -> groupClickData.id
- click시 받는 id값을 새로 넣어주었습니다. teamId가 있을경우엔 teamId, teamId가 없을 경우엔 clickId로 분기처리해서 버그 해결했습니다
-
-
-

teamId 문제 해결, 자유게시판 마진값 변경

---

src/components/Modal/ScheduleModal.tsx

Fix: Fix errors

---

src/components/Modal/IssuesModal.tsx
src/components/Modal/MyIssuesModal.tsx
src/components/common/modal/Comment.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/hooks/useIssue.ts
src/pages/UserIssuesPage.tsx
src/pages/team/TeamIssuesPage.tsx

- comment.tsx  reset()이용해서 post요청 이후 빈input만들고, 
- window.location.reload(); 부분 useAxios()로 수정했습니다! 참고하셔서 다른 부분도 작업 해주시면 감사하겠습니다
-
-
-

댓글 post요청 후 input창 reset, window.location.reload(); -> useAxios로 수정

---

src/components/Modal/ManageTeamHistoryModal.tsx
src/components/common/Nav.tsx
src/components/members/MemberTable.tsx

1. Nav바에 로그아웃 드롭다운 추가한 뒤로 프로필 아이콘 클릭이 안돼서 다시 수정했습니다
2. 마이페이지랑 멤버페이지 API 맞춰서 수정했습니다.
-
-
-

Fix: 마이페이지, 멤버페이지 API 맞춰 수정

---

src/components/Modal/AnnouncementModal.tsx
src/components/Modal/FreeBoardModal.tsx
src/components/Modal/MyIssuesModal.tsx
src/components/Modal/groupMemberInviteModal.tsx
src/components/Post/TeamPostList.tsx
src/components/Post/UserPostList.tsx
src/components/announcement/AnnouncementItem.tsx
src/components/announcement/AnnouncementList.tsx
src/components/announcement/AnnouncementPageList.tsx
src/components/kanbanBoard/IssueItem.tsx
src/components/kanbanBoard/IssueList.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/pages/UserMainPage.tsx
src/pages/UserPostsPage.tsx
src/pages/team/TeamAnnouncementsPage.tsx
src/pages/team/TeamIssuesPage.tsx
src/pages/team/TeamMainPage.tsx
src/pages/team/TeamPostsPage.tsx
src/types/announcementTypes.ts

- 모달 작업 후 리렌더링을 위해 window.location.reload() 함수 사용하던 부분 수정했습니다.
잘 됩니다!

Fix: window.location.reload() 함수 사용 부분 수정

---

src/components/Modal/ScheduleModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/ScheduleDeleteModal.tsx
src/components/SchedulesPage/ScheduleEditModal.tsx
src/components/common/TextButton.tsx
src/components/common/modal/ModalInput.tsx
src/components/common/modal/ModalLayout.tsx
src/components/common/modal/ModalScheduleCalendarInput.tsx
src/contexts/CalenarProvider.tsx

-일정 수정 모달 api연동해서 수정 가능하게 했습니다. 
-랜더링 되게끔은 아직 못했습니다.
-빌드시 나는 오류들 수정했습니다. 
-
-
-

일정수정 모달 기능 완료(랜더링X), 빌드시 오류 수정

---

src/pages/SigninPage.tsx

이번엔 프로덕션 모드에서도 import 되는 거 확인했습니다.
-
-
-

Fix: 로그인 페이지 이미지 import 수정

---

src/App.tsx
src/pages/LoadingPage.tsx

- 기존 빈 화면이었던 로딩페이지에 기본 레이아웃이라도 보일 수 있도록 로딩페이지 만들어두었습니다. 
- 화면 넘어갈 때마다 흰 화면 깜빡거리는 것보단 나은 것 같습니다 ㅎ.ㅎ
-
-

Feat: 로딩 페이지 추가

---

src/components/TeamsPage/TeamBar.tsx
src/components/common/Filter.tsx
src/components/kanbanBoard/IssueList.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/pages/UserIssuesPage.tsx

-
1. 대시보드 칸반보드 width 화면에 따라 늘어나도록
2. 팀/유저 칸반보드 레이아웃 통일
3. 초대 버튼 줄바꿈 방지
-
- 머지 되면 3번 잘 반영 되었는지 확인 부탁드립니다!

Design: 디자인 수정 및 변경 사항 반영

---

src/App.tsx
src/components/MainPage/MainSchedules.tsx
src/components/MainPage/WeekArr.tsx
src/components/MainPage/WeekDisplay.tsx
src/components/Modal/ScheduleModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/DateBox.tsx
src/components/SchedulesPage/ScheduleDeleteModal.tsx
src/components/SchedulesPage/ScheduleEditModal.tsx
src/components/SchedulesPage/Schedules.tsx
src/pages/NotFound.tsx

-404페이지 구현 
-주간 캘린더 오류 해결 
-
-
-

404페이지, 주간 캘린더 오류 해결

---

src/components/announcement/AnnouncementPageItem.tsx
src/components/chat/ChatInput.tsx

- 공지사항 읽음 버튼 추가 + 읽음 처리 api 연결
- 채팅 인풋 ui 수정 사항 반영하여 shadow 추가
-
-

Feat: 공지사항 읽음 버튼 추가 및 채팅 인풋 ui 수정

---

src/components/Modal/MyIssuesModal.tsx
src/components/Modal/groupMemberInviteModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/ControlDate.tsx
src/components/SchedulesPage/ScheduleEditModal.tsx
src/components/SchedulesPage/Time.tsx
src/components/common/modal/Comment.tsx
src/components/common/modal/CommentItem.tsx
src/components/common/modal/CommentPageination.tsx
src/components/common/modal/GroupList.tsx
src/components/common/modal/ModalCalendarInput.tsx
src/components/common/modal/ReplyItem.tsx
src/hooks/useIssue.ts

- 몇몇 콘솔 남기고 테스트용으로 만들어놓은 console.log 삭제했습니다 본인이 사용하는게 있으시다면 코멘트 남겨주세요!
-
-
-

console.log 삭제

---

src/components/SignupPage/EnterUserStepContent.tsx

4월 29일 채린님이 주신 피드백 반영했습니다.
-
-
-

Fix: 회원가입시 oauth로 받아온 사진이 있어도 빈 사진으로 뜨는 문제 수정
