.eslintrc.cjs
.prettierrc.json
package-lock.json
package.json

- Prettier 설치 및 설정
- ESLint에서 Prettier와의 충돌 방지
- x
[@trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) -> 프리티어 플러그인을 사용해서 import문이 뒤죽박죽 되지 않도록 정렬 순서를 지정해두었습니다. 일단 제 임의로 적당하다고 생각되는 순서대로 만들어질 폴더 이름 생각해서 지정해두었는데 사용하는 폴더 명이 달라지게 된다면 나중에 수정하겠습니다.
1. react, react-router 등의 라이브러리
2. 컴포넌트
1. 공통 컴포넌트
2. 그 외의 컴포넌트 
3. 함수 및 정의 파일
1. contexts 폴더 내 파일
2. lib 폴더 내 파일 (각종 함수)
3. hooks 폴더 내 파일
4. types 정의 파일
5. assets 폴더 (이미지 파일 등)
```
{
"importOrder": [
"^react",
"^[^@/](.*)$",
"^@/components/common(.*)$",
"^@/components/(.*)$",
"^@/contexts(.*)$",
"^@/lib/(.*)$",
"^@/hooks/(.*)$",
"^@/types/(.*)$",
"^@/assets/(.*)$",
"^[./]"
],
"importOrderSortSpecifiers": true
}
```
`prettier` - 프리티어
`@trivago/prettier-plugin-sort-imports` - import문 순서 자동 정렬해주는 프리티어 플러그인 …

style: Prettier 및 ESLint 세팅

---

public/check.svg
public/profile.svg
src/components/issue/IssueCards.tsx
src/components/issue/KanbanBoard.tsx
src/components/issue/TaskCard.tsx
src/components/issue/TaskCards.tsx
src/pages/TeamsPage.tsx

- 팀 페이지에 들어갈 칸반보드 컴포넌트 UI 구조 잡았습니다.
- 아직 와이어프레임 단계라 구조 위주로 잡고 UI적인 것은 신경 많이 안 썼습니다.
- 구조를 먼저 잡는 게 목적이었어서 prop이나 state로 관리하는 값은 아직 없습니다.
- 이슈 생성 버튼은 나중에 필겸님이 올려주신 공통 컴포넌트로 교체 예정입니다.
- 프로필 사진 겹쳐진 UI는 다른 곳에서도 많이 쓰여서 나중에 공통 컴포넌트로 분리해도 좋을 것 같습니다.
- 이 컴포넌트는 나중에 이슈 페이지에서 조금만 조정해서 사용할 수 있을 것 같습니다.
- 이미지 에셋들 모아놓는 파일을 src 폴더 안의 assets으로 정하면 어떨까 싶습니다. 소은님이 설정해주신 파일 경로 alias도 src 기준으로 하고 있어서 import 시에도 통일성이 있을 것 같습니다.

Design: 팀 페이지 - 칸반보드 UI 구조

---

src/components/Modal/AnnouncementModal.tsx
src/components/Modal/GroupEditModal.tsx
src/components/Modal/GroupModal.tsx
src/components/Modal/IssuesModal.tsx
src/components/TeamBar.tsx
src/components/announcement/AnnouncementBoard.tsx
src/components/announcement/AnnouncementCards.tsx
src/components/common/Nav.tsx
src/components/common/SideBar.tsx
src/components/issue/KanbanBoard.tsx
src/pages/TeamsPage.tsx

- 네비게이션바 & 사이드바를 추가한 팀 페이지 구조
- 각 버튼마다 링크 / 모달 연결
- 버튼 컴포넌트 공통 컴포넌트로 교체
- 스크린샷 참고
- 네비게이션 바, 사이드바는 항상 같은 자리에 있을 수 있도록 `fixed` 속성 추가해주었습니다.
-> 그래서 각자 작업하시는 페이지 마진값 조정해주시면 될 것 같습니다.
- 모달 바깥을 클릭하면 모달을 닫히게 하고 싶은데 계속 타입스크립트에서 막혀서 헤메다 결국 그 부분 빼고 pr 올립니다.
- 필겸님 모달 컴포넌트 보니까 바깥부분 클릭하면 닫히게 하는 함수를 프롭으로 내려주는 게 있던데 내일 여쭤볼게요! @MoonPillGyeom

Feat: 링크 및 모달창 버튼 클릭 이벤트 작업

---

src/App.tsx
src/components/Modal/AlertModal.tsx
src/components/ModalWrapper.tsx
src/components/common/ModalLayout.tsx
src/components/common/TextButton.tsx
src/contexts/ModalProvider.tsx
src/index.css
src/pages/SigninPage.tsx

1. modal 컨텐츠와 모달 열기/닫기 제어 함수를 관리하는 `<ModalContext/>`, `useModal` 훅 작성했습니다.
`<ModalWrapper/>`에 모달 외부 클릭, `esc`키 입력 시 닫기, 화면 중앙정렬, 이벤트리스너 클린업 기능을 분리해두었습니다.
2. 변경 사항 대비하여 모달 내 모달 띄우기, 모달 여러 개 띄우기가 가능하도록 하였습니다.
3. 기존 모달 시스템과 통합가능하도록 하였습니다. 제가 작성한 `<ModalWrapper/>`와 기존에 있던 `<ModalLayout/>`이랑 일부 기능이 겹치는 건 불가피했습니다. 그래도  `closeClick={close}` 만 붙여서 쓸 수 있어요...!
새로 모달컴포넌트 작성할 때는 `<ModalLayout/>` 없이 모달 내부만 작성해서 쓰시면 됩니다
4. 내부에 폼이 들어가는 모달이 아닌 단순 알림용 모달이 필요해서 스케치만 올려두었습니다.
- 제 로그인 페이지에서 확인 하실 수 있도록 해두었습니다. 
모달 사용법
```js
const SigninPage = () => {
const openModal = useModal();
const handleClickOpenModal = () => {
openModal(({ close }) => <GroupEditModal closeClick={close}></GroupEditModal>);
};
return (
<button className=" bg-teal-700 text-4xl" onClick={handleClickOpenModal} />
)};
```
- 현재 있는 것 외에 추가적으로 …

Feat: modal Context, usemodal 구현

---

.gitignore
src/components/MainPage/ControlDate.tsx
src/components/MainPage/DateBox.tsx
src/components/MainPage/MainSchedules.tsx
src/components/Modal/ScheduleModal.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/Schedules.tsx
src/pages/MainPage.tsx

-주간 캘린더 완성했습니다. 
-일 주일 단위 이동, 월 단위 이동 가능하게 했습니다. 
-
-지선님께서 로고 다운받아 놓으셨다고 해서 더 세부적인 스타일 요소는 내일 다시 업로드 하겠습니다. 
-내일 모달 기능, nav기능과 같이 PR올리겠습니다! 
-컴포넌트 폴더의 mainpage의  MainSchedules을 import하셔서 사용하면 됩니다. 
-혹시 문제점이나 수정사항이 있다면 말씀해주세요!

Feat: Make MainPage calendar UI

---

src/components/ModalWrapper.tsx
src/contexts/ModalProvider.tsx
src/pages/SigninPage.tsx

주석 달았습니다. 주석 남길 게 많아서 PR comment 달면 보기 불편하실 것 같아 내부에 달았습니다. 확인했다고 표시 해주시면 내부 코드 주석은 전부 지워서 commit 하나 더 남기고 머지하겠습니다.
**두 줄만 쓰시면 외부에서 컨텍스트 내부를 모르더라도 쓰시는데 지장 전혀 없도록 만들었습니다.** 바쁘신 분들 굳이 안 읽어주셔도 됩니다.
```js
const openModal = useModal();
const handleClickOpenModal = () => {
openModal(({ close }) => <GroupEditModal closeClick={close}></GroupEditModal>);
};
```
`({ close })` 부분은 내부 로직에 포함된 메소드라 이름 반드시 `close`로 지켜주셔야합니다. 이 외에는 다 변경해서 쓰시면 됩니다. `GroupEditModal`은 모달컴포넌트명, `closeClick`은 모달 닫는버튼의 핸들러의 이름으로 변경하시면 됩니다.
-
-
-

Refactor: 모달시스템 설명 주석 추가 및 리팩터링

---

src/components/common/SideBar/BoardList.tsx
src/components/common/SideBar/SideBar.tsx
src/components/common/SideBar/constants.ts

- 사이드바에 현재 열려있는 메뉴가 포커스 되도록 했습니다.
- 셀프 리뷰로 설명해놓겠습니다.
- 컨텍스트 생각하고 있었는데 아까 채빈님이 말씀해주신대로 pathname으로 받아오니 간단하게 해결되었습니다!

Feat: 사이드바 - 현재 페이지에 해당하는 버튼에 포커스 ui 적용

---

src/components/announcement/AnnouncementBoard.tsx
src/components/announcement/AnnouncementCards.tsx
src/components/common/BoardSection.tsx
src/components/common/SideBar/DropDown.tsx
src/components/common/SideBar/SideBar.tsx
src/components/common/ToolTip.tsx
src/components/kanbanBoard/IssueList.tsx
src/components/kanbanBoard/KanbanBoard.tsx
src/pages/MainPage.tsx

- 색상 변수 적용
- 1080 화면 사이즈에 맞춘 새로운 디자인에 맞추어 요소 높이 수정
- 스크린샷 참고
- 1080 사이즈에 맞추니 전체 화면 사이즈에서는 문제 없는데 브라우저 탭, 북마크 바가 있으면 이렇게 요소들이 아래로 밀려버리면서 레이아웃이 무너져 버리는 문제가 있습니다. 반응형 고려해서 높이 단위에 절대 단위 사용하지 않고 상대 단위 사용하려고 했는데 계속 해결되지 않아서 피그마대로 높이 지정해서 올립니다.

Design: 메인 페이지 ui 높이 수정 및 색상 변수 적용

---

tailwind.config.js

tailwind Typography 설정
폰트 사용시 `text-body1-bold`. 클래스명은 피그마시안 그대로 가져왔습니다.
-
폰트 클래스명 만들고, 에디터에서 자동완성 되도록 해두었습니다.
~~그냥 폰트 클래스명 레이어에 올리면 금방인데 그렇게하면 에디터에서 클래스명 자동완성이 안되길래... 쓰실 때 한참 불편할 것 같아서 intellisense에서 읽을 수 있게 하는 해결법 찾느라 오래걸렸습니다🥲🥲~~
~~혹시 나중에 다른 프로젝트할 때 같은 문제 겪으실 수 있으니
https://tailwindcss.com/docs/plugins
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/227
참고한 링크 붙여드립니다~~
theme에서 속성 여러 개 한번에 조정할 수 있길래 다시 수정했습니다🥲
-

Setting: tailwind Typography 설정

---

src/components/announcement/AnnouncementBoard.tsx
src/components/announcement/AnnouncementCards.tsx
src/components/common/NoCard.tsx
src/components/kanbanBoard/IssueList.tsx

- 카드 컴포넌트가 없을 때 보여줄 ui 추가 - 공통 컴포넌트로 분리했습니다.
```js
function NoCard({ children, backgroundColor }: NoCardProps) {
return (
<div
className={`relative flex h-64 flex-col items-center justify-center rounded-[2.4rem] bg-${backgroundColor} p-[2.4rem]`}
>
<span className="text-[1.4rem] font-bold text-gray50">{children}</span>
</div>
);
}
```
```js
<NoCard backgroundColor="white">공지사항이 없습니다.</NoCard>
```
-

Design: 카드 컴포넌트가 없을 때 보여줄 ui 추가

---

src/components/MainPage/MainSchedules.tsx
src/components/ModalCalenar/ModalCalendar.tsx
src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/ControlDate.tsx
src/components/SchedulesPage/DateBox.tsx
src/components/SchedulesPage/Schedules.tsx
src/components/common/BoardSection.tsx
src/contexts/CalenarProvider.tsx
src/pages/TeamSchedulesPage.tsx

-메인 페이지 캘린더 UI 수정
-모달 캘린더 UI 완료 
-    
`  <div className="h-[20.1rem] w-[22.5rem] px-[1.4rem] py-[1.3rem]">//이부분은 따로 필겸님이 추가해주세요!
<ModalCalendar />// w,h 둘다 full로 줬습니다. 그냥 import해오셔서 쓰면 될거에요~
</div>`
-메인 페이지  피그마 그대로 적용시 화면에서 이상하게 보여서 제가 gap범위 알아서 수정했습니다. 지현님께 낼 말씀드리겠습니다. 
-필겸님은 한번 모달에 적용해보시면 될 것 같습니다.

메인페이지 캘린더 UI 수정, 모달 캘린더 UI 완성

---

src/App.tsx
src/components/SignupPage/EnterUserStepContent.tsx
src/components/SignupPage/SignupLayout.tsx
src/components/SignupPage/ToSStepContent.tsx
src/components/common/Input.tsx
src/hooks/useAxios.ts
src/pages/OauthRedirectPage.tsx
src/pages/SigninPage.tsx
src/pages/SignupPage.tsx
src/types/user.ts

1. useAxios 타입 수정해서 리스폰스 프로퍼티 못 잡고 린팅에러 나는 부분 해결했습니다.
2. 소셜로그인 구현했습니다. 각자 테스트 해보시면 됩니다.
3. Signup 페이지 포함 갈아엎은 부분이 많다보니까 추상화가 전혀 안되어 있습니다. 읽기 불편하시면 리팩터링 기다렸다가 해주세요... 우선 급한 구현부터 해결하겠습니다. 
4. **PR 못 쪼개서 죄송합니다** 건들게 너무 많았어요
```js
interface UseAxiosParams<T> {
path?: string;
method?: Method;
data?: T | Record<string, never>;
}
export const useAxios = <T = unknown, P = unknown, E = unknown>(
{ path = '', method = 'GET', data = {} }: UseAxiosParams<P>,
shouldFetch: boolean = false,
) => {
const [state, setState] = useState<{
loading: boolean;
error: AxiosError<E> | null;
data: T | null;
}>({
```
`T` 가 `reponse data` 타입, `P`가 `requset payload` 타입입니다. `E`가 `error` 타입입니다. 혹시 문제있으면 말씀해주세요!
지금 소셜로그인까지 되는데 signin PUT 500 에러나는 상태라 signin 리다이렉트되는거 무시하고 
**담당 페이지 직접 url 쳐서 들어가셔서 테스트 해주세요.**
signin이 …

Feat: 소셜로그인 구현 & Refactor: useAxios 타입 수정

---

src/components/common/BoardSection.tsx
src/components/posts/BulletinBoard.tsx
src/components/posts/Post.tsx
src/mockdata/postData.ts
src/pages/TeamsPostsPage.tsx
src/types/postTypes.ts

- 자유게시판 페이지 UI 구현
- api 연동은 아직이고 목데이터 만들어 작업했습니다.
- 댓글이랑 고정 기능은 회의 때 일단 없는 걸로 얘기 된 부분이라 ui에 넣진 않았습니다. 나중에 디자인 수정되면 고치겠습니다.

Design: 자유게시판 페이지 UI 구현

---

src/hooks/useAxios.ts
src/pages/OauthRedirectPage.tsx

axios interceptors로 토큰 갱신 구현.
-
로그아웃 시, refreshToken 만료 시 제외, accessToken 만료되어도 refreshToken으로 갱신하고 기존 요청에 대한 응답 그대로 받아올 있도록 구현. 로그인이나 재요청 없어도 되도록. 
api 연결하다보니까 회원가입 폼에서 생각보다 걸리는 부분이 많아서 일단 로그인 시 다 메인으로 리다이렉트 되게끔도 변경해놓았습니다.
-

Feat: 토큰 갱신 로직 구현

---

src/components/SchedulesPage/AllDay.tsx
src/components/SchedulesPage/ControlDate.tsx
src/components/SchedulesPage/GroupFilter.tsx
src/components/SchedulesPage/Schedules.tsx
src/components/common/BoardSection.tsx
src/contexts/CalenarProvider.tsx
src/pages/TeamSchedulesPage.tsx
src/pages/team/TeamCalendar.tsx

-나의 캘린더 필터 기능에 맞춰 데이터 넣기 빼기 가능 
-팀 캘린더 캘린더 안에 데이터 불러오기 성공
-
-
-문제점이 컬러가 반영이 안되고 있어서 이부분 계속 수정해야 할 것 같습니다. ..
-캘린더 타입을 CalendrProvider파일에 합쳐 놓았는데 이렇게 하는 게 잘 한건가요? 데이터는 잘 불러져 옵니다 (유저아이디로 데이터 불러오기, 팀 아이디로 데이터 불러오기 데이터 구조를 합친 것 입니다!)
-혹시 이외의 수정사항이 있다면 말씀해 주세요 .. ㅎ

Fix: 나의 캘린더, 팀 캘린더 페이지 데이터 연동

---

src/constants/Page.tsx

- 페이지 경로에서 페이지 이름을 복수 명사에서 단수 명사로 변경했습니다.
- 백엔드와 통일하기 위해 이렇게 했습니다.
-
- 
- 아마 다른 분들 영향은 없을 것 같습니다.
- 채빈님께서 상수화 이어서 작업하셔야 해서 바로 머지하겠습니다~

Fix: 페이지 경로에서 페이지 이름을 복수 명사에서 단수 명사로 변경

---

src/assets/PageArrowLeftIcon.tsx
src/assets/PageArrowRightIcon.tsx
src/components/Post/PostList.tsx
src/components/announcement/AnnouncementPageList.tsx
src/components/common/BoardSection.tsx
src/components/common/pagenation/PageNumber.tsx
src/components/common/pagenation/Pagenation.tsx
src/constants/Page.tsx
src/contexts/PageProvider.tsx
src/hooks/useAnnouncement.ts
src/hooks/usePost.ts
src/pages/UserMainPage.tsx
src/pages/UserPostsPage.tsx
src/pages/team/TeamAnnouncementsPage.tsx
src/pages/team/TeamMainPage.tsx
src/pages/team/TeamPostsPage.tsx

- 페이지네이션 구현해서 공지사항, 자유게시판 페이지에 적용해두었습니다.
- 페이지네이션 사용하는 페이지들은 페이지 상수에서 PageProvider로 감싸주었습니다.
- 구체적인 구현 사항 설명은 셀프 리뷰로 남겨두겠습니다.
- 지금 PageProvider 안에 로직이 if문으로 분기하는 부분도 많고 몹시 지저분합니다... 마음에는 안 들지만 일단은 동작하게는 만들어두었는데 우선은 이 정도 선에서 PR 올리고 개선은 나중에 해보는 걸로 하겠습니다.

Feat: 페이지네이션 구현

---

src/components/Post/PostList.tsx
src/components/TeamsPage/TeamTab.tsx
src/components/announcement/AnnouncementPageList.tsx
src/components/common/BoardSection.tsx
src/components/common/ProfileStack.tsx
src/components/common/sideBar/SideBar.tsx
src/components/kanbanBoard/KanbanBoard.tsx

- 자잘한 문제들 수정
- 디자인에는 없기는 한데 작은 화면에서 타이틀 보이지 않는 문제는 해결해야 할 것 같아서 임의로 반응형 줬습니다.
⬇️
⬇️
-

Fix: 자잘한 UI 문제들 수정 및 백엔드 요청 경로 수정 사항 반영

---

src/components/Modal/EditProfileModal.tsx
src/components/SignupPage/EnterUserStepContent.tsx
src/components/SignupPage/SignupLayout.tsx
src/hooks/useAxios.ts

- 유저네임 확인 후 유효할 시 인풋 아래 초록색 valid message 뜨도록.
- 기존 유저네임을 유지한 상태로도 폼을 변경할 수 있도록
- 이전 중복 확인으로 ok 응답을 얻었더라도 다른 유저네임을 제출 시도 시 폼 제출이 불가하도록.
https://github.com/codeit-part4-8team-project/main/assets/121015462/eedcb300-1078-4ef8-aa54-ce63d2f20cda
-
-

Feat: 유저 정보 편집 폼 유효성 검증 업데이트

---

package-lock.json
src/components/Modal/ManageTeamHistoryModal.tsx
src/components/Mypage/DeleteAccountButton.tsx
src/components/common/ItemDropDown.tsx
src/components/common/LogoutDropDown.tsx
src/components/common/Nav.tsx
src/components/common/SelectBoxDropdown.tsx
src/components/members/MemberRow.tsx
src/pages/UserMyPage.tsx

1. 회원탈퇴 구현
2. 로그아웃 구현
3. 팀 삭제, 회원 탈퇴 DELETE는 API 수정되면 정상 동작할 것 같습니다 
---
기존에 지선님이 만들어 주신 `ItemDropdown` 컴포넌트 재사용해서 로그아웃 구현했습니다.
디자인 시안에서 프로필 아이콘이랑 드롭다운이랑 갭이 있어서 지선님 ItemDropdown에 classname 부분 추가하고 소은님 navbar에 드롭다운 달리는 부분 추가했습니다 확인해주세요!
---
드롭다운 구분지으려고 드롭다운 이름 ui 맞게 바꿨습니다
`Dropdown` > `SelectBoxDropdown`
`ItemDropdown`
-
-
-

Feat: 회원탈퇴, 로그아웃 구현
